export enum MatchStates {
  "dormiant" = "DORMIANT",
  "building" = "BUILDING",
  "builded" = "BUILDED",
  "waiting_p1_join" = "WAITING_P1_JOIN",
  "waiting_p2_join" = "WAITING_P2_JOIN",
  "waiting_p1_ready" = "WAITING_P1_READY",
  "waiting_p2_ready" = "WAITING_P2_READY",
  "match_ready" = "READY",
  "started" = "STARTED",
  "waiting_p1_move" = "WAITING_P1_MOVE",
  "p1_move" = "P1_MOVE",
  "waiting_p2_move" = "WAITING_P2_MOVE",
  "p2_move" = "P2_MOVE",
  "terminated" = "TERMINATED",
  "pending" = "PENDING",
  "error" = "ERROR",
}