export enum MatchStates {
  dormiant = "DORMIANT",
  building = "BUILDING",
  builded = "BUILDED",
  waiting_players_ready = "WAITING_PLAYERS_REEADY",
  match_ready = "READY",
  started = "STARTED",
  in_play = "IN_PLAY",
  waiting_player_move = "WAITING_PLAYER_MOVE",
  shaking_board = "SHAKING_BOARD",
  checking_sequence = "CHECKING_SEQUENCE",
  sequence_found = "SEQUENCE_FOUND",
  checking_game_status = "CHECKING_GAME_STATUS",
  terminated = "TERMINATED",
  resetting = "RESETTING",
  pending = "PENDING",
  error = "ERROR",
}