export enum MatchStates {
  dormiant = "DORMIANT",
  building = "BUILDING",
  builded = "BUILDED",
  waiting_players_ready = "WAITING_PLAYERS_READY",
  ready = "READY",
  starting = "STARTING",
  started = "STARTED",
  waiting_for_player_move = "WAITING_FOR_PLAYER_MOVE",
  shaking_board = "SHAKING_BOARD",
  checking_sequence = "CHECKING_SEQUENCE",
  sequence_found = "SEQUENCE_FOUND",
  checking_game_status = "CHECKING_GAME_STATUS",
  terminated = "TERMINATED",
  resetting = "RESETTING",
  player_left_the_room = "PLAYER_LEFT_THE_ROOM",
  pending = "PENDING",
  error = "ERROR",
}